version: '3.8'
services:
  website:
    build: ./website
    ports:
      - "8080:80"
    networks:
      - app-network

  api:
    build: ./api
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres-service:5432/messagesdb
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=messagesdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
